version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
        - "5432:5432"

  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: api_container
    ports:
      - "6969:6969"
    environment:
      DB_HOST: postgres
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    depends_on:
      - postgres
    command: ["/wait-for-it.sh", "postgres_db:5432", "--", "node", "server.js"]

  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    container_name: website_container
    ports:
      - "80:80"
    environment:
      DB_HOST: postgres
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    depends_on:
      - postgres

volumes:
  postgres_data:
